"""Meta-labeling: a second model that sizes/vetoes the first one's trades.

Lopez de Prado (AFML ch.3): keep the primary model for DIRECTION, then
train a secondary classifier on "did acting on this signal make money net
of costs?" and use its calibrated probability for bet sizing. Replicated
gains (Hudson & Thames): precision 0.48 -> 0.54 on the same primary.

The training set is generated by REPLAYING the primary model's signals
through the exact live exit stack (policy_exits.exit_walk — the same
kernel the backtester and the TB labels use) at a LOWERED entry threshold,
so the meta model sees plenty of marginal trades it should learn to
reject. The final ~12% of rows — a row-quantile approximation of the
hypersearch holdout, recomputed here over the full harvest frame rather
than read from hypersearch (which derives its boundary from a possibly
--max-rows-capped row set) — is excluded from meta training so the
policy-backtest gate stays honest; the resolved cutoff is recorded in
meta_meta.json so drift between the two boundaries is observable.

KNOWN LIMITS (2026-07 panel, owner queue): the replay's entry population
diverges from the deployed policy beyond the deliberate threshold
lowering (no cost/edge floor, no post-hard-stop lockout, no stock entry
windows, no q10 veto — see _gen_meta_rows), and the 'pred' feature is the
primary's IN-SAMPLE fitted value on its own training window (rev-07-01
"meta in-sample-primary leak") — no calibration mode can remove that.
2026-08 R2: META_OOF_PRED (uses persisted walk-forward OOF predictions when
fresh) and META_REPLAY_POLICY_PARITY (applies the live admission conditions
to the replay) address these behind default-OFF flags; meta_meta.json stamps
pred_source and replay-parity diagnostics unconditionally.

Live use (both loops + backtest, for policy parity):
  - p < META_VETO_PROB (0.30): skip the entry
  - otherwise size tilt = clip(2p, 0.6, 1.3)  (p=0.5 -> neutral 1.0x)

Usage:
    python meta_label.py --prefix stock      # train after the primary
    python meta_label.py                     # crypto
    python meta_label.py --no-publish        # write {prefix}meta_*.staged only
    python meta_label.py --promote-staged    # guard-check + promote .staged

Guarded-publish contract (2026-08 R1, D13a/D13b): training now stages the
artifact triple, runs degenerate-calibrator guards, and only then atomically
promotes staged -> live. A refusal leaves the previous consistent live triple
(or the fail-open-neutral absence) untouched and writes {prefix}meta_refused.json.
"""

import argparse
import json
import math
import os
import sys
from pathlib import Path

import numpy as np

BASE_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(BASE_DIR))

META_VETO_PROB = 0.30
META_THRESHOLD_FRACTION = 0.5   # replay entries at 0.5x live threshold
HOLDOUT_FRACTION = 0.12         # keep in sync with hypersearch_v2

# Feature names must exist BOTH in the harvest dataframe and in the live
# prediction snapshot (predict_now._SNAPSHOT_COLS) — plus the prediction
# itself and the entry hour. Missing values become 0.0 on both sides.
META_FEATURES = [
    'pred', 'RSI', 'Price_SMA20_Ratio', 'BBB_20_2.0', 'Volatility_12h',
    'Return_4h', 'Return_12h', 'ATR_Pct', 'Daily_Sentiment', 'Hurst',
    'hour_sin', 'hour_cos',
    # Return-of-day (BDS 2025): SOFT feature only — the meta-learner can
    # discover the PM-window loser-bounce interaction with hour_sin/cos;
    # a hard rule died in red-team (winner-leg effect is ~0)
    'ROD_Ret',
]


def _paths(prefix: str) -> dict:
    p = f'{prefix}_' if prefix else ''
    return {
        'model': BASE_DIR / f'{p}meta_model.txt',
        'calib': BASE_DIR / f'{p}meta_calib.pkl',
        'meta': BASE_DIR / f'{p}meta_meta.json',
        'refused': BASE_DIR / f'{p}meta_refused.json',
    }


# ---------------------------------------------------------------------------
# Publish guards + guarded staged->live promotion (2026-08 R1, D13a/D13b)
# ---------------------------------------------------------------------------

META_GUARD_MIN_CALIB_N = 10       # matches calibration.fit_calibrator
META_GUARD_MAX_FRAC_VETO = 0.8    # existing warning threshold, now a refusal
META_GUARD_MIN_P_RANGE = 0.01     # constant-output detector (existing warning)
META_GUARD_MIN_VAL_AUC = 0.50     # refuse WORSE-than-chance; 0.55 stays a warning
                                  # (the 0.55 skill floor remains an owner decision)


def _calib_slice_guard(raw_val, y_slice) -> str | None:
    """Pre-fit guards for ANY calibration sample (mirror of fit_calibrator's
    degenerate guards, applied to the legacy same-slice branch — D13a).
    Returns a refusal reason or None."""
    raw_val = np.asarray(raw_val, float)
    y_slice = np.asarray(y_slice, float)
    if raw_val.size < META_GUARD_MIN_CALIB_N:
        return f'calib_slice_too_thin(n={raw_val.size})'
    if np.unique(y_slice).size < 2:
        return 'calib_slice_one_class'
    if np.unique(raw_val).size < 2:
        return 'calib_slice_constant_scores'
    return None


def _publish_guard_reasons(p_all, val_auc, frac_veto) -> list[str]:
    """Post-fit refusal reasons on the calibrated-p distribution + skill.
    A constant p=0.0 vetoes the whole book; ~1.0 boosts everything (D13a)."""
    reasons = []
    p_all = np.asarray(p_all, float)
    if float(np.max(p_all) - np.min(p_all)) < META_GUARD_MIN_P_RANGE:
        reasons.append(f'constant_calibrated_p(range<{META_GUARD_MIN_P_RANGE})')
    if frac_veto >= META_GUARD_MAX_FRAC_VETO:
        reasons.append(f'frac_below_veto={frac_veto:.2f}>={META_GUARD_MAX_FRAC_VETO}')
    if val_auc is not None and val_auc < META_GUARD_MIN_VAL_AUC:
        reasons.append(f'val_auc={val_auc:.3f}<{META_GUARD_MIN_VAL_AUC}')
    return reasons


def _calibration_v2_on() -> bool:
    try:
        import strategy_config as _sc
        return bool(getattr(_sc, 'CALIBRATION_V2', False))
    except Exception:
        return False


def _calibration_embargo() -> float:
    """Purge embargo for the OOF calibration split. B04.1 (binding): 0.05
    fractional-of-fold-span (entry/exit are epoch SECONDS, so this is 5% of
    the fold's absolute time span). Legacy passes 0.0 (no embargo)."""
    return 0.05 if _calibration_v2_on() else 0.0


# ---------------------------------------------------------------------------
# OOF primary predictions (2026-08 R2, D12 / B04.1) — pure, Mac-tested helpers
# ---------------------------------------------------------------------------

OOF_MIN_ROWS = 200             # below this the OOF path falls back to in-sample
OOF_FULL_PARAMS_MIN_ROWS = 1000
OOF_SHRUNK_PARAMS = {'num_leaves': 8, 'max_depth': 3, 'feature_fraction': 0.6}


def oof_pack_from_folds(fold_rows, fold_preds, fold_ids, all_times_s, tickers,
                        ticker_boundaries, holdout_boundary_s) -> dict:
    """Assemble the persistable OOF-prediction pack from per-fold val arrays.

    Pure numpy. `fold_rows`/`fold_preds` are per-fold lists of GLOBAL row
    indices + predictions (hypersearch _train_walk_forward's val slices);
    `all_times_s` is the epoch-SECONDS row-time array (load_data convention);
    `ticker_boundaries` maps name -> (start, end) contiguous global rows.
    Rows past `holdout_boundary_s` are dropped DEFENSIVELY even though
    get_walk_forward_folds already excludes the holdout — the npz must
    NEVER contain holdout-slice predictions.
    """
    if fold_ids is None:
        fold_ids = list(range(len(fold_rows)))
    rows_l, preds_l, fids_l = [], [], []
    for fid, rows, preds in zip(fold_ids, fold_rows, fold_preds):
        rows = np.asarray(rows, dtype=np.int64)
        preds = np.asarray(preds, dtype=np.float32).ravel()
        if len(rows) != len(preds):
            raise ValueError(f'oof_pack_from_folds: fold {fid} rows '
                             f'({len(rows)}) != preds ({len(preds)})')
        rows_l.append(rows)
        preds_l.append(preds)
        fids_l.append(np.full(len(rows), int(fid), dtype=np.int16))
    rows = np.concatenate(rows_l) if rows_l else np.empty(0, np.int64)
    preds = np.concatenate(preds_l) if preds_l else np.empty(0, np.float32)
    fids = np.concatenate(fids_l) if fids_l else np.empty(0, np.int16)
    all_times_s = np.asarray(all_times_s, dtype=np.int64)
    keep = all_times_s[rows] <= int(holdout_boundary_s)
    rows, preds, fids = rows[keep], preds[keep], fids[keep]
    starts = np.array([ticker_boundaries[t][0] for t in tickers],
                      dtype=np.int64)
    tick_idx = np.searchsorted(starts, rows, side='right') - 1
    return {
        'ticker': np.asarray(tickers, dtype=np.str_)[tick_idx],
        'ts_ns': all_times_s[rows] * 10 ** 9,
        'oof_pred': preds.astype(np.float32),
        'fold_id': fids,
    }


def write_oof_npz(path, pack, saved_at, score) -> None:
    """Atomic tmp+os.replace npz write, fingerprinted to the manifest's
    saved_at + round-4 score. Caller handles exceptions (fail-soft)."""
    tmp = f'{path}.tmp.{os.getpid()}'
    try:
        with open(tmp, 'wb') as f:
            np.savez_compressed(
                f, ticker=pack['ticker'], ts_ns=pack['ts_ns'],
                oof_pred=pack['oof_pred'], fold_id=pack['fold_id'],
                saved_at=np.array(str(saved_at)),
                score=np.array(round(float(score), 4)))
        os.replace(tmp, path)
    finally:
        try:
            os.unlink(tmp)   # no-op after a successful replace
        except OSError:
            pass


def load_oof_npz(path, manifest) -> tuple:
    """(pack, status); status in {'ok','missing','stale','unreadable'}.

    'ok' requires the npz fingerprint (saved_at string-equal, score equal
    within 1e-9 — both sides store round(score, 4)) to match the CURRENT
    champion manifest; anything else is 'stale' and the caller falls back
    loudly to the in-sample path. numpy + stdlib only.
    """
    if not os.path.exists(path):
        return None, 'missing'
    try:
        with np.load(path, allow_pickle=False) as z:
            required = ('ticker', 'ts_ns', 'oof_pred', 'saved_at', 'score')
            if any(k not in z.files for k in required):
                return None, 'unreadable'
            pack = {k: np.asarray(z[k]) for k in
                    ('ticker', 'ts_ns', 'oof_pred', 'fold_id')
                    if k in z.files}
            npz_saved_at = str(z['saved_at'])
            npz_score = float(z['score'])
    except Exception:
        return None, 'unreadable'
    if manifest is None:
        return None, 'stale'
    if npz_saved_at != manifest.get('saved_at'):
        return None, 'stale'
    try:
        if abs(npz_score - float(manifest.get('score'))) > 1e-9:
            return None, 'stale'
    except (TypeError, ValueError):
        return None, 'stale'
    return pack, 'ok'


def join_oof_to_index(index_ns, ticker, pack) -> np.ndarray:
    """Per-row OOF prediction for one ticker's bar index; NaN outside
    coverage (the OOF consumer DROPS those rows — never backfills).
    index_ns is floored to whole seconds before matching: the pack's ts_ns
    are seconds-truncated (load_data's // 10**9). Pure numpy."""
    index_ns = np.asarray(index_ns, dtype=np.int64)
    floored = (index_ns // 10 ** 9) * 10 ** 9
    out = np.full(len(index_ns), np.nan, dtype=np.float64)
    sel = pack['ticker'] == str(ticker)
    ts = np.asarray(pack['ts_ns'][sel], dtype=np.int64)
    if ts.size == 0:
        return out
    vals = np.asarray(pack['oof_pred'][sel], dtype=np.float64)
    order = np.argsort(ts, kind='stable')
    ts_s, vals_s = ts[order], vals[order]
    # Dedupe keeping the LAST occurrence (defensive: fold val slices are
    # time-disjoint by construction, so (ticker, ts) keys are unique).
    keep = np.ones(ts_s.size, dtype=bool)
    keep[:-1] = ts_s[1:] != ts_s[:-1]
    ts_s, vals_s = ts_s[keep], vals_s[keep]
    pos = np.searchsorted(ts_s, floored)
    in_range = pos < ts_s.size
    hit = np.where(in_range)[0]
    hit = hit[ts_s[pos[hit]] == floored[hit]]
    out[hit] = vals_s[pos[hit]]
    return out


def oof_starvation_tier(n_rows) -> tuple:
    """B04.3 binding tiers: ('starved', None) below OOF_MIN_ROWS,
    ('shrunk', param overrides) below OOF_FULL_PARAMS_MIN_ROWS,
    ('full', None) otherwise."""
    n = int(n_rows)
    if n < OOF_MIN_ROWS:
        return 'starved', None
    if n < OOF_FULL_PARAMS_MIN_ROWS:
        return 'shrunk', dict(OOF_SHRUNK_PARAMS,
                              min_data_in_leaf=max(20, n // 20))
    return 'full', None


def _notify(msg: str):
    """Best-effort (shadow.py pattern) — a notify failure never blocks."""
    try:
        from notify import notify
        notify(msg, level='warning', dedupe_key=f'meta-{msg[:40]}')
    except Exception:
        pass


def _write_refusal(paths: dict, reasons: list, extra: dict | None = None):
    """{prefix}meta_refused.json sidecar (tmp+os.replace, never raises) —
    instrumentation for the refusal path; live triple untouched."""
    try:
        tmp = None
        import datetime as _dt
        path = paths.get('refused')
        if path is None:   # test seams build their own dicts without the key
            path = Path(str(paths['meta'])).with_name(
                Path(str(paths['meta'])).name.replace('meta_meta.json',
                                                      'meta_refused.json'))
        payload = {
            'refused_at': _dt.datetime.now(_dt.timezone.utc).isoformat(),
            'reasons': list(reasons),
            **(extra or {}),
        }
        tmp = f'{path}.tmp.{os.getpid()}'
        with open(tmp, 'w') as f:
            json.dump(payload, f, indent=2, default=str)
        os.replace(tmp, path)
    except Exception as e:
        if tmp:
            try:
                os.unlink(tmp)
            except OSError:
                pass
        print(f"[META] refusal sidecar write failed ({e}) — refusal still holds")


def promote_staged_meta(prefix: str = '') -> bool:
    """Guarded, atomic staged->live promotion (D13b). The ONLY path that may
    replace live meta artifacts. Refusal leaves the existing live triple (or
    the fail-open-neutral absence) untouched."""
    import shutil
    paths = _paths(prefix)
    staged = {k: Path(str(paths[k]) + '.staged') for k in ('model', 'calib', 'meta')}
    missing = [k for k in staged if not staged[k].exists()]
    if missing:
        print(f"[META] staged promote REFUSED: missing staged {missing}")
        _notify(f"[META] {prefix or 'crypto'} staged promote refused: "
                f"missing staged {missing}")
        return False
    try:
        with open(staged['meta']) as f:
            payload = json.load(f)
    except Exception as e:
        print(f"[META] staged promote REFUSED: staged meta unreadable ({e})")
        _notify(f"[META] {prefix or 'crypto'} staged promote refused: "
                f"staged meta unreadable")
        return False
    calib_prov = payload.get('calibration') or {}
    if calib_prov.get('publish_guards_ok') is not True:
        print(f"[META] staged promote REFUSED: guards not passed "
              f"({calib_prov.get('guard_reasons')}) — previous live triple "
              f"(or neutral fail-open) retained")
        _notify(f"[META] {prefix or 'crypto'} staged promote refused: "
                f"guards not passed")
        _write_refusal(paths, ['staged_guards_not_ok'],
                       {'calibration': calib_prov})
        return False
    # Primary-pairing freshness: refuse if the champion manifest changed
    # since staging (the staged meta's 'pred' feature belongs to that primary)
    fp = payload.get('primary')
    if fp and fp.get('manifest_mtime_ns') is not None:
        p_pre = f'{prefix}_' if prefix else ''
        mpath = BASE_DIR / f'{p_pre}model_v2.manifest.json'
        try:
            cur = os.stat(mpath).st_mtime_ns
        except OSError:
            cur = None
        if cur != fp['manifest_mtime_ns']:
            print("[META] staged promote REFUSED: primary manifest changed "
                  "since staging — retrain required")
            _notify(f"[META] {prefix or 'crypto'} staged promote refused: "
                    f"primary manifest changed since staging")
            return False
    # .prev backups of the CURRENT live triple (moved here from train_meta —
    # rollback pairs are made at the moment live is replaced)
    for key in ('model', 'calib', 'meta'):
        if paths[key].exists():
            try:
                shutil.copy2(paths[key], str(paths[key]) + '.prev')
            except OSError as e:
                print(f"[META] WARNING: .prev backup failed for "
                      f"{paths[key].name}: {e} — the rollback pair may be "
                      f"incomplete or mismatched")
    # Atomic renames, meta -> calib -> model (existing publish order convention)
    try:
        os.replace(staged['meta'], paths['meta'])
        os.replace(staged['calib'], paths['calib'])
        os.replace(staged['model'], paths['model'])
    except OSError as e:
        print(f"[META] staged promote FAILED mid-rename ({e}) — inspect "
              f"triple consistency")
        _notify(f"[META] {prefix or 'crypto'} staged promote FAILED "
                f"mid-rename — inspect triple consistency")
        return False
    # housekeeping: clear shadow.py's rename-aside stale files, if any
    for key in ('model', 'calib', 'meta'):
        try:
            os.unlink(str(paths[key]) + '.stale')
        except OSError:
            pass
    invalidate_cache()
    print(f"[META] staged artifacts promoted to live: {paths['model'].name}, "
          f"{paths['calib'].name}, {paths['meta'].name}")
    return True


# ---------------------------------------------------------------------------
# Feature construction (single source for training + live)
# ---------------------------------------------------------------------------

def _hour_encode(hour: float) -> tuple[float, float]:
    ang = 2 * math.pi * hour / 24.0
    return math.sin(ang), math.cos(ang)


def build_feature_matrix(tdf, preds) -> np.ndarray:
    """Per-bar meta features from a harvest-style DataFrame (training)."""
    n = len(tdf)
    preds = np.asarray(preds, dtype=np.float64)
    if preds.shape != (n,):
        raise ValueError(f'build_feature_matrix: preds shape {preds.shape} '
                         f'!= len(tdf) {n}')
    # Single hour pass feeding both trig columns — vectorized twin of
    # _hour_encode (the live scalar path); keep the two in sync.
    hours = (tdf.index.hour.to_numpy(dtype=np.float64)
             if hasattr(tdf.index, 'hour')
             else np.array([t.hour for t in tdf.index], dtype=np.float64))
    hour_ang = 2 * np.pi * hours / 24.0
    cols = {}
    for name in META_FEATURES:
        if name == 'pred':
            cols[name] = preds
        elif name == 'hour_sin':
            cols['hour_sin'] = np.sin(hour_ang)
        elif name == 'hour_cos':
            cols['hour_cos'] = np.cos(hour_ang)
        elif name in tdf.columns:
            cols[name] = tdf[name].values.astype(np.float64)
        else:
            cols[name] = np.zeros(n, dtype=np.float64)
    mat = np.column_stack([cols[name] for name in META_FEATURES])
    return np.nan_to_num(mat, nan=0.0, posinf=0.0, neginf=0.0)


def features_from_snapshot(snapshot: dict, pred: float,
                           hour: float | None = None) -> np.ndarray:
    """Live feature vector from the loop's indicator snapshot."""
    if hour is None:
        from datetime import datetime, timezone
        hour = datetime.now(timezone.utc).hour
    hs, hc = _hour_encode(hour)
    vals = []
    for name in META_FEATURES:
        if name == 'pred':
            vals.append(float(pred) if pred is not None else 0.0)
        elif name == 'hour_sin':
            vals.append(hs)
        elif name == 'hour_cos':
            vals.append(hc)
        else:
            v = snapshot.get(name)
            try:
                v = float(v)
                if not np.isfinite(v):
                    v = 0.0
            except (TypeError, ValueError):
                v = 0.0
            vals.append(v)
    return np.asarray(vals, dtype=np.float64)


# ---------------------------------------------------------------------------
# Live / backtest scoring
# ---------------------------------------------------------------------------

_loaded: dict[str, tuple] = {}   # prefix -> (artifact stat key, result)


def _stat_key(paths: dict) -> tuple:
    """(model_mtime_ns, calib_mtime_ns); None for a missing file.

    The key changes when artifacts are retrained, deleted (shadow
    promotion), or first appear — so _load self-heals without a restart.
    """
    key = []
    for k in ('model', 'calib'):
        try:
            key.append(os.stat(paths[k]).st_mtime_ns)
        except OSError:
            key.append(None)
    return tuple(key)


def _read_artifacts(paths: dict) -> tuple:
    """Load (booster, calibrator) from disk. Split out so tests can stub it."""
    import joblib
    import lightgbm as lgb
    booster = lgb.Booster(model_file=str(paths['model']))
    calib = joblib.load(paths['calib'])
    return booster, calib


def _check_feature_schema(paths: dict) -> None:
    """WARN (only) when the on-disk manifest's feature list no longer matches
    META_FEATURES. LightGBM matches numpy columns by POSITION, so a
    same-length reorder silently scores the wrong columns with no exception
    anywhere. Enforcement (disabling the layer on drift) is an owner
    decision; this is the tripwire. Missing/unreadable meta.json is silent.
    """
    try:
        if not paths['meta'].exists():
            return
        with open(paths['meta']) as f:
            stored = json.load(f).get('features')
        if stored is not None and list(stored) != list(META_FEATURES):
            print(f"[META] WARNING: feature schema drift — disk={stored} "
                  f"code={META_FEATURES}; served p may be scoring the wrong "
                  f"columns (LightGBM matches by position)")
    except Exception:
        pass


def _load(prefix: str):
    """(booster, calib) for `prefix`, or None when the meta layer is absent.

    Cache contract (2026-07 review P1): keyed on the artifact files'
    mtimes, re-stat'd on every call (two os.stat per candidate — cheap).
    A weekly meta retrain, a shadow promotion that DELETES the champion
    meta files (the gate then fails open to neutral, per shadow.py), or
    the first meta train landing in an already-running bot all take
    effect without a process restart. A load failure is cached as None
    under the same key (no per-bar retry storm) and retried as soon as
    the files change.
    A re-stat after each successful read closes the torn-pair window left
    by the two-file publish (see the publish block).
    """
    paths = _paths(prefix)
    key = _stat_key(paths)
    cached = _loaded.get(prefix)
    if cached is not None and cached[0] == key:
        return cached[1]
    result = None
    if None not in key:
        try:
            result = _read_artifacts(paths)
        except Exception as e:
            print(f"[META] load failed ({e}) — meta layer disabled")
            result = None
        if result is not None:
            # Torn-pair guard (2026-07 panel): the publisher swaps calib and
            # model in two separate os.replace calls and _stat_key wakes on
            # EITHER mtime, so a read landing between the swaps pairs the new
            # calibrator with the old booster. Re-stat after reading; if the
            # key moved, read once more under the new key.
            key2 = _stat_key(paths)
            if key2 != key:
                key = key2
                result = None
                if None not in key2:
                    try:
                        result = _read_artifacts(paths)
                    except Exception as e:
                        print(f"[META] load failed ({e}) — meta layer disabled")
                        result = None
        if result is not None:
            global _calib_fallback_warned, _nonfinite_p_warned
            _calib_fallback_warned = False   # warn-once is per loaded artifact
            _nonfinite_p_warned = False
            _check_feature_schema(paths)
    _loaded[prefix] = (key, result)
    return result


def invalidate_cache():
    global _calib_fallback_warned, _nonfinite_p_warned
    _loaded.clear()
    # Warn-once flags are per artifact generation, not per process (the bots
    # never stop): re-arm them whenever the cache is invalidated.
    _calib_fallback_warned = False
    _nonfinite_p_warned = False


_calib_fallback_warned = False
_nonfinite_p_warned = False


def _calibrated(calib, raw: np.ndarray) -> np.ndarray:
    global _calib_fallback_warned
    try:
        return np.clip(calib.predict(raw), 0.0, 1.0)
    except Exception as e:
        if not _calib_fallback_warned:
            _calib_fallback_warned = True
            print(f"[META] calibrator predict failed ({e}) — serving raw scores")
        return np.clip(raw, 0.0, 1.0)


def meta_probability_live(prefix: str, snapshot: dict, pred: float) -> float | None:
    """Calibrated P(trade profits net of costs) for a live candidate.

    Returns None when no meta model exists — the layer is strictly
    optional and absent models leave behavior unchanged.
    """
    global _nonfinite_p_warned
    loaded = _load(prefix)
    if loaded is None:
        return None
    booster, calib = loaded
    x = features_from_snapshot(snapshot, pred).reshape(1, -1)
    raw = booster.predict(x)
    p = float(_calibrated(calib, np.asarray(raw))[0])
    if not np.isfinite(p):
        # calibration.py's contract: "predict propagates non-finite raw as
        # NaN — callers must guard." Unguarded, base_loop's veto (NaN < x is
        # False) passes AND its tilt clamp max(0.1, min(TILT_MAX, nan))
        # resolves to TILT_MAX — the MAXIMUM boost. Serve the documented
        # neutral (None) instead.
        if not _nonfinite_p_warned:
            _nonfinite_p_warned = True
            print("[META] non-finite calibrated probability — served as None "
                  "(neutral)")
        return None
    return p


def predict_meta_array(prefix: str, tdf, preds) -> np.ndarray | None:
    """Per-bar meta probabilities for the backtester (policy parity)."""
    loaded = _load(prefix)
    if loaded is None:
        return None
    booster, calib = loaded
    try:
        mat = build_feature_matrix(tdf, preds)
        raw = booster.predict(mat)
        return _calibrated(calib, np.asarray(raw))
    except Exception as e:
        # backtest.py wraps this call in a bare `except Exception: pass` —
        # emit the reason HERE so a present-but-broken meta layer cannot
        # silently turn the promotion gate's veto into a no-op.
        print(f"[META] scoring failed ({e}) — meta gate disabled for this frame")
        return None


def meta_size_mult(p: float | None) -> float:
    """Bounded sizing multiplier from the calibrated probability.

    Non-finite p is treated as None -> neutral 1.0: np.clip propagates NaN,
    and base_loop's max(0.1, min(TILT_MAX, tilt)) resolves a NaN tilt to
    TILT_MAX (the maximum boost), so this guard is load-bearing.
    """
    if p is None or not np.isfinite(p):
        return 1.0
    return float(np.clip(2.0 * p, 0.6, 1.3))


# ---------------------------------------------------------------------------
# Training
# ---------------------------------------------------------------------------

def _meta_payload(n_trades, base_rate, val_auc, holdout_cutoff_utc,
                  n_rows_total, n_rows_pre_cutoff, n_tickers_used,
                  skipped_tickers, zero_filled_features, net_summary,
                  calibration, primary, trained_at,
                  pred_source='in_sample', oof=None,
                  replay_parity=None) -> dict:
    """Assemble the meta_meta.json payload (pure dict builder — unit-tested
    on the dev Mac). The first five keys are the legacy schema, kept
    byte-compatible; the file is write-only repo-wide, so additions are
    contract-safe."""
    return {
        'features': list(META_FEATURES),
        'n_trades': int(n_trades),
        'base_win_rate': round(float(base_rate), 4),
        'val_auc': round(float(val_auc), 4) if val_auc is not None else None,
        'threshold_fraction': META_THRESHOLD_FRACTION,
        'trained_at': trained_at,
        'holdout_cutoff_utc': holdout_cutoff_utc,
        'n_rows_total': int(n_rows_total),
        'n_rows_pre_cutoff': int(n_rows_pre_cutoff),
        'n_tickers_used': int(n_tickers_used),
        'n_tickers_skipped': len(skipped_tickers),
        'skipped_tickers': [[t, r] for t, r in list(skipped_tickers)[:40]],
        'zero_filled_features': list(zero_filled_features),
        'net_summary': net_summary,
        'calibration': calibration,
        'primary': primary,
        'pred_source': pred_source,
        'oof': oof,
        'replay_parity': replay_parity,
    }


def _gen_meta_rows(tdf, preds, asset_type, threshold, policy, *,
                   entry_preds=None, parity=False, entry_ok=None,
                   q10_preds=None, q10_floor=None, diag=None):
    """Replay the primary's signals through the live exit stack.

    Entries at META_THRESHOLD_FRACTION x the live threshold so the meta
    model also sees the marginal signals it should learn to veto.
    Returns (features, labels, net_returns, entry_times, exit_times).

    `entry_preds` (OOF, META_OOF_PRED) replaces `preds` for ADMISSION and
    the 'pred' feature only — `preds` still drives exit_walk (signal-exit
    inputs are label semantics; changing them is beyond B04.1's binding).

    KNOWN DIVERGENCES from the deployed entry policy (2026-07 panel — the
    threshold relaxation above is the only DELIBERATE one): closed under
    META_REPLAY_POLICY_PARITY (parity=True) — required_edge_pct floor,
    post-hard-stop lockout, stock entry windows (entry_ok), q10 tail veto
    (q10_preds/q10_floor); legacy population when False. Both populations'
    row counts + per-condition first-fail drop counts land in `diag` (dict,
    updated in place) regardless of the flag.
    """
    from policy_exits import exit_walk, eod_mask_from_index, REASON_NAMES
    from fees import round_trip_cost_pct, required_edge_pct

    closes = tdf['Close'].values
    highs = tdf['High'].values if 'High' in tdf.columns else closes
    lows = tdf['Low'].values if 'Low' in tdf.columns else closes
    opens = tdf['Open'].values if 'Open' in tdf.columns else closes
    atr = tdf['ATR'].values if 'ATR' in tdf.columns else np.full(len(closes), np.nan)
    is_eod = eod_mask_from_index(tdf.index, asset_type)

    spread = 0.10 if asset_type == 'crypto' else 0.05
    rt_cost = round_trip_cost_pct(asset_type, spread)
    # Per-bar effective-spread cost when the harvest stamped it (wave 6):
    # removes the train/deploy asymmetry vs the real-spread live gate. Falls
    # back to the flat rt_cost per bar when Eff_Spread_Pct is absent.
    rt_cost_arr = None
    if 'Eff_Spread_Pct' in tdf.columns:
        try:
            from liquidity import per_bar_round_trip_cost, impact_inputs_from_df
            # Optional sqrt market-impact haircut (wave-8 #6), off by default so
            # the meta labels are unchanged unless explicitly enabled + DV30 present.
            adv_arr, impact_notional, impact_k = impact_inputs_from_df(tdf)
            rt_cost_arr = per_bar_round_trip_cost(
                asset_type, tdf['Eff_Spread_Pct'].values,
                adv_dollar=adv_arr, notional=impact_notional, impact_k=impact_k)
        except Exception as e:
            print(f"[META] per-bar spread cost failed ({e}) — flat-cost fallback")
            rt_cost_arr = None
    cooldown_bars = max(1, int(math.ceil(policy['cooldown_min'] / 60)))
    entry_threshold = threshold * META_THRESHOLD_FRACTION
    edge_floor = required_edge_pct(asset_type, spread)   # flat spread —
    # backtest.simulate_ticker convention (live admission uses the real quote)
    hard_stop_code = next(k for k, v in REASON_NAMES.items()
                          if v == 'hard_stop')
    lockout_bars = int(policy['lockout_hours'])   # backtest bar convention

    exit_idx, exit_px, reason_code = exit_walk(
        closes, highs, lows, opens, atr, is_eod, policy,
        preds=preds, threshold=threshold, cooldown_bars=cooldown_bars,
        max_hold=0, use_signal_exit=True)

    # sel drives ADMISSION and the 'pred' FEATURE; preds still drives the
    # exit walk above (signal exits / label semantics unchanged).
    sel = preds if entry_preds is None else np.asarray(entry_preds, float)
    feats_all = build_feature_matrix(tdf, sel)
    n = len(closes)

    def _walk(use_parity):
        """Entry walk over the precomputed exit arrays. use_parity=False is
        the exact legacy population; True mirrors simulate_ticker's
        admission stack with FIRST-FAIL drop counting."""
        pairs = []
        drops = {'lockout': 0, 'edge_floor': 0, 'entry_window': 0, 'q10': 0}
        i = 0
        next_entry_plain = 0    # legacy tracker: plain cooldown only
        next_entry_locked = 0   # parity tracker: hard-stop lockout extension
        while i < n - 1:
            p = sel[i]
            if (np.isnan(p) or i < next_entry_plain or p < entry_threshold
                    or is_eod[i]):
                i += 1
                continue
            if use_parity:
                # Fixed first-fail order for the drop counters
                # (simulate_ticker parity)
                if i < next_entry_locked:
                    drops['lockout'] += 1
                    i += 1
                    continue
                if p < edge_floor:
                    drops['edge_floor'] += 1
                    i += 1
                    continue
                if entry_ok is not None and not entry_ok[i]:
                    drops['entry_window'] += 1
                    i += 1
                    continue
                if (q10_preds is not None and q10_floor is not None
                        and not np.isnan(q10_preds[i])
                        and q10_preds[i] < q10_floor):
                    drops['q10'] += 1
                    i += 1
                    continue
            j = int(exit_idx[i])
            pairs.append((i, j))
            cooldown_after = cooldown_bars
            if use_parity and int(reason_code[i]) == hard_stop_code:
                cooldown_after = max(cooldown_bars, lockout_bars)
            next_entry_plain = j + cooldown_bars
            next_entry_locked = j + cooldown_after
            i = j + 1
        return pairs, drops

    legacy_pairs, _ = _walk(False)
    parity_pairs, drops = _walk(True)
    active_pairs = parity_pairs if parity else legacy_pairs

    rows, labels, nets, times, exit_times = [], [], [], [], []
    for i, j in active_pairs:
        cost_i = rt_cost if rt_cost_arr is None else float(rt_cost_arr[i])
        net = (float(exit_px[i]) - closes[i]) / closes[i] * 100.0 - cost_i
        rows.append(feats_all[i].copy())  # copy: a view would pin the whole per-ticker matrix in RAM
        labels.append(1 if net > 0 else 0)
        nets.append(net)
        times.append(tdf.index[i])
        exit_times.append(tdf.index[j])   # label span end, for the purged calibration
    if isinstance(diag, dict):
        diag.update({
            'rows_legacy': len(legacy_pairs),
            'rows_parity': len(parity_pairs),
            'drops': drops,
            'edge_floor_pct': edge_floor,
            'n_bars': n,
            'n_covered': int(np.isfinite(np.asarray(sel, float)).sum()),
        })
    return rows, labels, nets, times, exit_times


def train_meta(prefix: str = '', publish: bool = True) -> bool:
    import joblib
    try:
        import lightgbm as lgb
    except ImportError:
        print("[META] lightgbm not installed — skipping meta layer")
        return False
    from sklearn.isotonic import IsotonicRegression
    from data_utils import load_training_data
    from strategy_config import policy_for
    from backtest import (_load_artifacts, _predict_ticker, _load_lgb,
                          _load_q10, _entry_window_mask)
    import datetime as _dt

    asset_type = prefix or 'crypto'
    try:
        model, scaler, config, feature_cols = _load_artifacts(prefix)
    except FileNotFoundError:
        print("[META] primary model artifacts missing — train the primary first")
        return False
    lgb_primary = _load_lgb(prefix)
    threshold = config.get('trade_threshold', 0.15)
    policy = policy_for(asset_type)

    # --- 2026-08 R2 (D12 / D05-meta) flag + artifact wiring -----------------
    import strategy_config as _sc
    _oof_on = bool(getattr(_sc, 'META_OOF_PRED', False))
    _parity_on = bool(getattr(_sc, 'META_REPLAY_POLICY_PARITY', False))
    # Champion manifest, read ONCE for the OOF fingerprint check. The later
    # primary_fp block deliberately re-reads (its mtime_ns freshness-token
    # semantics must not change).
    p_pre = f'{prefix}_' if prefix else ''
    _manifest = None
    try:
        with open(BASE_DIR / f'{p_pre}model_v2.manifest.json') as _mf:
            _manifest = json.load(_mf)
    except Exception:
        _manifest = None
    # ALWAYS load for the status stamp (instrumentation); consume only on flag.
    oof_pack, oof_status = load_oof_npz(BASE_DIR / f'{p_pre}oof_preds.npz',
                                        _manifest)
    use_oof = _oof_on and oof_status == 'ok'
    # q10 tail model — parity input only (extra booster inference is gated
    # on the flag: Jetson 8GB memory priority).
    q10_model, q10_floor = None, None
    if _parity_on:
        pack_ = _load_q10(prefix)
        if pack_:
            q10_model, q10_floor = pack_
    _q10_scored = q10_model is not None

    df = load_training_data('stock' if prefix == 'stock' else 'crypto')
    if df.empty:
        print("[META] no training data")
        return False

    # META_FEATURES absent from the harvest frame are zero-filled on EVERY
    # row by build_feature_matrix — the booster then trains without that
    # signal while live keeps feeding real values. Values unchanged; record.
    zero_filled = [c for c in META_FEATURES
                   if c not in ('pred', 'hour_sin', 'hour_cos')
                   and c not in df.columns]
    if zero_filled:
        print(f"[META] WARNING: features absent from the training frame, "
              f"zero-filled on every row: {zero_filled}")

    # Exclude the hypersearch holdout (final 12% by ROW time-quantile — an
    # approximation of hypersearch's boundary, which is computed over a
    # possibly --max-rows-capped row set; recorded so drift is observable)
    times_ns = df.index.astype('int64')
    cutoff = np.quantile(times_ns, 1.0 - HOLDOUT_FRACTION)
    n_rows_total = int(len(df))
    n_rows_pre_cutoff = int((np.asarray(times_ns) <= cutoff).sum())
    cutoff_iso = _dt.datetime.fromtimestamp(int(cutoff) / 1e9,
                                            _dt.timezone.utc).isoformat()

    X, y, net_list, ts, exit_ts = [], [], [], [], []
    # In-sample fallback population, built in the same pass when the OOF
    # path is active (predictions dominate cost; rows are 13 floats each).
    X_is, y_is, net_is, ts_is, exit_ts_is = [], [], [], [], []
    diag_tot = {'rows_legacy': 0, 'rows_parity': 0, 'n_bars': 0,
                'n_covered': 0, 'edge_floor_pct': None,
                'drops': {'lockout': 0, 'edge_floor': 0,
                          'entry_window': 0, 'q10': 0}}
    skipped, n_used = [], 0
    # groupby(sort=False) preserves first-appearance order — identical row
    # order to the old df['Ticker'].unique() + boolean-mask loop (order is
    # LOAD-BEARING, see the argsort note below) — without a full-frame mask
    # scan per ticker.
    for ticker, tdf in df.groupby('Ticker', sort=False):
        tdf = tdf.sort_index()
        tdf = tdf[tdf.index.astype('int64') <= cutoff]
        if len(tdf) < config['seq_len'] + 50:
            skipped.append((str(ticker), 'too_short'))
            continue
        missing = [c for c in feature_cols if c not in tdf.columns]
        if missing:
            skipped.append((str(ticker),
                            'missing_cols:' + ','.join(missing[:3])))
            continue
        preds, _ = _predict_ticker(model, scaler, config, feature_cols, tdf,
                                   lgb_model=lgb_primary, q10_model=q10_model)
        q10_arr = _   # q10 leg of the pair (None unless q10_model was passed;
        # the `preds, _ =` unpack shape is pinned by test_review_b14's arity pin)
        entry_ok = (_entry_window_mask(tdf.index)
                    if asset_type == 'stock' else None)
        oof_row_preds = (join_oof_to_index(tdf.index.astype('int64'),
                                           str(ticker), oof_pack)
                         if use_oof else None)
        tk_diag = {}
        r, l, nr, t, et = _gen_meta_rows(
            tdf, preds, asset_type, threshold, policy,
            entry_preds=oof_row_preds, parity=_parity_on, entry_ok=entry_ok,
            q10_preds=q10_arr, q10_floor=q10_floor, diag=tk_diag)
        X.extend(r); y.extend(l); net_list.extend(nr)
        ts.extend(t); exit_ts.extend(et)
        for k in ('rows_legacy', 'rows_parity', 'n_bars', 'n_covered'):
            diag_tot[k] += tk_diag.get(k, 0)
        for k in diag_tot['drops']:
            diag_tot['drops'][k] += tk_diag.get('drops', {}).get(k, 0)
        diag_tot['edge_floor_pct'] = tk_diag.get('edge_floor_pct')
        if use_oof:
            r2, l2, nr2, t2, et2 = _gen_meta_rows(
                tdf, preds, asset_type, threshold, policy,
                entry_preds=None, parity=_parity_on, entry_ok=entry_ok,
                q10_preds=q10_arr, q10_floor=q10_floor, diag=None)
            X_is.extend(r2); y_is.extend(l2); net_is.extend(nr2)
            ts_is.extend(t2); exit_ts_is.extend(et2)
        n_used += 1
        print(f"  [META] {ticker}: {len(r)} replayed trades")
    # Free the harvest frame and the primary BEFORE LightGBM allocates —
    # this subprocess shares the 8 GB Jetson with the live bots.
    del df, model, scaler, lgb_primary, q10_model, oof_pack
    if skipped:
        counts = {}
        for _, reason in skipped:
            k2 = reason.split(':', 1)[0]
            counts[k2] = counts.get(k2, 0) + 1
        print(f"[META] skipped {len(skipped)}/{len(skipped) + n_used} "
              f"tickers: {counts} (first: {skipped[0][0]} {skipped[0][1]})")

    # OOF starvation tiering (B04.3 binding — fallback tiering, never a hard
    # refusal). base rates captured BEFORE any fallback swap.
    base_rate_oof = (round(float(np.mean(y)), 4)
                     if (use_oof and len(y)) else None)
    base_rate_is = (round(float(np.mean(y_is)), 4)
                    if (use_oof and len(y_is)) else None)
    pred_source, oof_fallback_reason, tier, tier_overrides = \
        'in_sample', None, None, None
    if _oof_on:
        if use_oof:
            tier_name, tier_overrides = oof_starvation_tier(len(X))
            if tier_name == 'starved':
                print(f"[META] pred feature is IN-SAMPLE (OOF rows starved: "
                      f"n={len(X)} < {OOF_MIN_ROWS}) — falling back to the "
                      f"in-sample population")
                oof_fallback_reason = f'oof_starved(n={len(X)})'
                X, y, net_list, ts, exit_ts = X_is, y_is, net_is, ts_is, exit_ts_is
            else:
                pred_source, tier = 'oof', tier_name
        else:
            print("[META] pred feature is IN-SAMPLE (OOF preds missing/stale)")
            oof_fallback_reason = f'oof_{oof_status}'
    elif oof_status == 'ok':
        print("[META] OOF preds present and fresh but META_OOF_PRED is OFF — "
              "pred feature is IN-SAMPLE")

    if len(X) < 200:
        print(f"[META] only {len(X)} replayed trades — not enough to train")
        return False

    # NOTE (2026-07 panel): row order here is LOAD-BEARING. np.argsort's
    # default quicksort is UNSTABLE and cross-ticker entry timestamps tie on
    # the shared hourly grid, so within-tie order (hence the 0.8 split, the
    # purged fold cuts, and lgb's row-order-dependent bagging) is an artifact
    # of ticker iteration order. Do NOT switch to kind='stable' or change the
    # ts dtype casually — that changes the trained artifact (model-facing).
    order = np.argsort(np.asarray(ts))
    X = np.asarray(X)[order]
    y = np.asarray(y)[order]
    split = int(len(X) * 0.8)  # chronological split for early stop + calibration
    train_set = lgb.Dataset(X[:split], label=y[:split],
                            feature_name=META_FEATURES)
    val_set = lgb.Dataset(X[split:], label=y[split:], reference=train_set)
    params = {
        'objective': 'binary', 'metric': 'auc',
        'num_leaves': 31, 'max_depth': 5, 'learning_rate': 0.05,
        'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5,
        'verbose': -1, 'n_jobs': 4,
    }
    if tier == 'shrunk':
        # B04.3 shrunk tier for the thinner honest-OOF population
        # (overrides computed once by oof_starvation_tier).
        params.update(tier_overrides)
    booster = lgb.train(params, train_set, num_boost_round=400,
                        valid_sets=[val_set],
                        callbacks=[lgb.early_stopping(30, verbose=False)])

    # Probability calibration. Default 'legacy' = the original same-slice isotonic
    # (the leak: it fits on the exact X[split:] slice the booster early-stopped on).
    # 'purged_oof' (wave-9 #1) calibrates on PURGED out-of-fold predictions,
    # removing the meta booster's same-slice leak. Residual, per
    # calibration.crossfit_oof_predict's own caveat: n_iter below is the
    # FULL-SAMPLE early-stopped round count captured into every fold closure —
    # closing that (per-fold early stop) is an owner decision. Fail-open to legacy.
    from strategy_config import META_CALIBRATION_MODE
    calib = None
    calib_prov = {'mode_requested': META_CALIBRATION_MODE, 'used': 'legacy',
                  'fallback_reason': None, 'oof_rows': None,
                  'embargo': _calibration_embargo(),
                  'calibration_v2': _calibration_v2_on()}
    if META_CALIBRATION_MODE == 'purged_oof':
        try:
            from calibration import crossfit_oof_predict, fit_calibrator
            entry_e = np.array([t.timestamp() for t in np.asarray(ts)[order]], float)
            exit_e = np.array([t.timestamp() for t in np.asarray(exit_ts)[order]], float)
            n_iter = int(booster.best_iteration or 200)

            def _fold_fit_predict(Xtr, ytr, Xte):
                ds = lgb.Dataset(Xtr, label=ytr, feature_name=META_FEATURES)
                b = lgb.train(params, ds, num_boost_round=n_iter)
                return b.predict(Xte)

            oof = crossfit_oof_predict(_fold_fit_predict, X, y, entry_e, exit_e,
                                       k=5, embargo=_calibration_embargo())
            calib = fit_calibrator(oof, y)
            if calib is not None:
                calib_prov['used'] = 'purged_oof'
                calib_prov['oof_rows'] = int(np.isfinite(oof).sum())
                print(f"[META] purged out-of-fold calibration "
                      f"({type(calib).__name__}, {calib_prov['oof_rows']} OOF rows)")
            else:
                # fit_calibrator DECLINED (thin/one-class/constant OOF). This
                # fallback used to be silent — the wave-9 A/B could measure
                # legacy-vs-legacy without knowing it.
                calib_prov['fallback_reason'] = 'fit_calibrator declined'
                print("[META] purged calibration declined by fit_calibrator — "
                      "falling back to legacy same-slice isotonic")
        except Exception as e:
            print(f"[META] purged calibration failed ({e}) — falling back to legacy")
            calib_prov['fallback_reason'] = f'{type(e).__name__}: {e}'
            calib = None
    paths = _paths(prefix)
    if calib is None:
        if calib_prov['fallback_reason'] is not None:
            calib_prov['used'] = 'legacy_fallback'
        raw_val = booster.predict(X[split:])
        reason = _calib_slice_guard(np.asarray(raw_val), y[split:])   # D13a: the
        # legacy same-slice fit previously had NO degenerate guards — a one-class
        # 20% tail published a constant p (0.0 vetoes the book for a week).
        if reason is not None:
            calib_prov['guard_reasons'] = [reason]
            print(f"[META] REFUSING to publish: {reason} — the previous meta "
                  f"artifact triple stays live (refusal is safer than a "
                  f"degenerate calibrator)")
            _notify(f"[META] {prefix or 'crypto'} publish refused: {reason}")
            _write_refusal(paths, [reason], {'calibration': calib_prov})
            return False
        if _calibration_v2_on():
            # CALIBRATION_V2 (B04.2): size-aware chooser instead of raw sklearn
            # isotonic on a 40-100-point slice (isotonic-overfit regime).
            from calibration import fit_calibrator as _fit_cal
            calib = _fit_cal(np.asarray(raw_val), np.asarray(y[split:], float))
            if calib is None:
                reason = 'fit_calibrator_declined_legacy_slice'
                calib_prov['guard_reasons'] = [reason]
                print(f"[META] REFUSING to publish: {reason} — the previous "
                      f"meta artifact triple stays live (refusal is safer "
                      f"than a degenerate calibrator)")
                _notify(f"[META] {prefix or 'crypto'} publish refused: "
                        f"{reason}")
                _write_refusal(paths, [reason], {'calibration': calib_prov})
                return False
            calib_prov['legacy_fit'] = 'fit_calibrator'
        else:
            calib = IsotonicRegression(out_of_bounds='clip').fit(raw_val, y[split:])
    calib_prov['calibrator'] = type(calib).__name__
    for attr, out_key in (('method_', 'method'), ('n_fit_', 'n_fit'),
                          ('n_dropped_', 'n_dropped'), ('base_rate_', 'base_rate')):
        calib_prov[out_key] = getattr(calib, attr, None)
    # Calibrated-p distribution over the training rows (measurement only): a
    # collapsed calibrator (e.g. a one-class calibration slice) serves a
    # near-constant p and can silently veto or boost the whole book.
    p_all = _calibrated(calib, np.asarray(booster.predict(X)))
    frac_veto = float(np.mean(p_all < META_VETO_PROB))
    calib_prov.update({
        'p_min': round(float(np.min(p_all)), 4),
        'p_median': round(float(np.median(p_all)), 4),
        'p_max': round(float(np.max(p_all)), 4),
        'frac_below_veto': round(frac_veto, 4),
    })
    if frac_veto >= 0.8 or float(np.max(p_all) - np.min(p_all)) < 0.01:
        print(f"[META] WARNING: degenerate calibrated-p distribution "
              f"(min {float(np.min(p_all)):.3f}, max {float(np.max(p_all)):.3f}, "
              f"{frac_veto:.0%} below the {META_VETO_PROB} veto) — inspect the "
              f"calibration slice before trusting this artifact")
    auc = booster.best_score.get('valid_0', {}).get('auc')
    val_auc = float(auc) if auc is not None else None
    if val_auc is not None and val_auc < 0.55:
        print(f"[META] WARNING: val AUC {val_auc:.3f} is near chance — "
              f"artifacts publish anyway (a skill floor is an owner decision)")

    # Post-fit publish guards (D13a): the warnings above fire first with
    # detail; refusal follows. Both purged and legacy calibrators pass here.
    calib_prov['guard_reasons'] = _publish_guard_reasons(p_all, val_auc,
                                                         frac_veto)
    calib_prov['publish_guards_ok'] = not calib_prov['guard_reasons']
    if calib_prov['guard_reasons']:
        print(f"[META] REFUSING to publish: {calib_prov['guard_reasons']} — "
              f"previous meta triple stays live")
        _notify(f"[META] {prefix or 'crypto'} publish refused: "
                f"{calib_prov['guard_reasons']}")
        _write_refusal(paths, calib_prov['guard_reasons'],
                       {'calibration': calib_prov, 'val_auc': val_auc,
                        'n_trades': len(X)})
        return False

    # (.prev backups moved into promote_staged_meta — rollback pairs are
    # made at the moment live is replaced, D13b)

    # Primary fingerprint: which primary these meta artifacts pair with —
    # also the promote-time freshness token (promote_staged_meta refuses
    # when the champion manifest changed since staging).
    primary_fp = None
    try:
        p_pre = f'{prefix}_' if prefix else ''
        mpath = BASE_DIR / f'{p_pre}model_v2.manifest.json'
        if mpath.exists():
            with open(mpath) as mf:
                man = json.load(mf)
            primary_fp = {'manifest_mtime_ns': os.stat(mpath).st_mtime_ns,
                          'saved_at': man.get('saved_at'),
                          'score': man.get('score')}
    except Exception as e:
        print(f"[META] primary manifest unreadable ({e}) — no fingerprint")
        primary_fp = None

    base_rate = float(np.mean(y))
    net_arr = np.asarray(net_list, dtype=np.float64)
    net_summary = {
        'mean_pct': round(float(net_arr.mean()), 4),
        'median_pct': round(float(np.median(net_arr)), 4),
        'p10_pct': round(float(np.percentile(net_arr, 10)), 4),
        'p90_pct': round(float(np.percentile(net_arr, 90)), 4),
    }
    payload = _meta_payload(
        n_trades=len(X), base_rate=base_rate, val_auc=val_auc,
        holdout_cutoff_utc=cutoff_iso, n_rows_total=n_rows_total,
        n_rows_pre_cutoff=n_rows_pre_cutoff, n_tickers_used=n_used,
        skipped_tickers=skipped, zero_filled_features=zero_filled,
        net_summary=net_summary, calibration=calib_prov, primary=primary_fp,
        trained_at=_dt.datetime.now(_dt.timezone.utc).isoformat(),
        pred_source=pred_source,
        oof={'status': oof_status, 'consume_flag': _oof_on,
             'n_active_rows': len(X),
             'n_in_sample_rows': (len(X_is) if use_oof else len(X)),
             'coverage_frac': (round(diag_tot['n_covered']
                                     / diag_tot['n_bars'], 4)
                               if use_oof and diag_tot['n_bars'] else None),
             'tier': tier, 'fallback_reason': oof_fallback_reason,
             'base_rate_oof': base_rate_oof,
             'base_rate_in_sample': base_rate_is},
        replay_parity={'enabled': _parity_on,
                       'rows_legacy': diag_tot['rows_legacy'],
                       'rows_parity': diag_tot['rows_parity'],
                       'drops': diag_tot['drops'],
                       'edge_floor_pct': diag_tot['edge_floor_pct'],
                       'q10_scored': _q10_scored})
    # Pred composition provenance (c26 final review): OOF preds are the
    # LSTM leg only (hypersearch persists fold val outputs pre-blend), while
    # live serves the meta gate the lstm_weight BLEND — the in-sample path
    # matches serving by construction. Stamped so llm_eval/decision_report
    # can attribute drift; write-only file, contract-safe additive key.
    payload['pred_composition'] = ('lstm_only' if pred_source == 'oof'
                                   else 'blend')

    # Stage order meta -> calib -> model, each via tmp + os.replace so a
    # reader never sees a half-written file; PID-suffixed tmp names so
    # concurrent trains cannot clobber each other's tmp (hypersearch_v2's own
    # convention). All payload/metadata work happens BEFORE any replace, so
    # an exception leaves the previous consistent triple live. The targets
    # are the .staged triple (D13b): live artifacts are only ever replaced
    # by promote_staged_meta, the ONE guarded staged->live path. NOTE:
    # _stat_key covers model AND calib mtimes, so a reader can wake on the
    # calib swap and momentarily read (old model, new calib) — _load's
    # re-stat retry closes that torn-pair window; strict cross-file atomicity
    # would need a single-file manifest (deferred).
    pid = os.getpid()
    staged = {k: Path(str(paths[k]) + '.staged') for k in ('model', 'calib', 'meta')}
    tmp_model = f"{staged['model']}.tmp.{pid}"
    tmp_calib = f"{staged['calib']}.tmp.{pid}"
    tmp_meta = f"{staged['meta']}.tmp.{pid}"
    try:
        with open(tmp_meta, 'w') as f:
            json.dump(payload, f, indent=2)
        booster.save_model(tmp_model)
        joblib.dump(calib, tmp_calib)
        os.replace(tmp_meta, staged['meta'])
        os.replace(tmp_calib, staged['calib'])
        os.replace(tmp_model, staged['model'])
    finally:
        for leftover in (tmp_meta, tmp_calib, tmp_model):
            try:
                os.unlink(leftover)
            except OSError:
                pass
    if not publish:
        print(f"[META] staged only (--no-publish): {staged['model'].name} — "
              f"promote with --promote-staged")
        return True
    ok = promote_staged_meta(prefix)   # the ONE guarded staged->live path (D13b)
    if not ok:
        return False
    auc_str = f"{val_auc:.3f}" if val_auc is not None else "n/a"
    print(f"[META] saved {paths['model'].name}: {len(X)} trades, "
          f"base win-rate {base_rate:.3f}, val AUC {auc_str}")
    return True


if __name__ == '__main__':
    ap = argparse.ArgumentParser(description='Train the meta-labeling layer')
    ap.add_argument('--prefix', default='', choices=['', 'stock'],
                    help="'' crypto, 'stock' stocks")
    ap.add_argument('--no-publish', action='store_true',
                    help='train and write {prefix}meta_*.staged only; never '
                         'touch live artifacts')
    ap.add_argument('--promote-staged', action='store_true',
                    help='skip training; guard-check + atomically promote '
                         'existing .staged artifacts')
    args = ap.parse_args()
    if args.promote_staged:
        promote_staged_meta(args.prefix)
    else:
        train_meta(args.prefix, publish=not args.no_publish)  # graceful False is non-fatal in the pipeline
    sys.exit(0)  # NOTE: an uncaught crash still exits 1 — crash-tolerance is decision-queued
