"""Meta-labeling: a second model that sizes/vetoes the first one's trades.

Lopez de Prado (AFML ch.3): keep the primary model for DIRECTION, then
train a secondary classifier on "did acting on this signal make money net
of costs?" and use its calibrated probability for bet sizing. Replicated
gains (Hudson & Thames): precision 0.48 -> 0.54 on the same primary.

The training set is generated by REPLAYING the primary model's signals
through the exact live exit stack (policy_exits.exit_walk — the same
kernel the backtester and the TB labels use) at a LOWERED entry threshold,
so the meta model sees plenty of marginal trades it should learn to
reject. The final 12% of calendar time (the hypersearch holdout) is
excluded from meta training so the policy-backtest gate stays honest.

Live use (both loops + backtest, for policy parity):
  - p < META_VETO_PROB (0.30): skip the entry
  - otherwise size tilt = clip(2p, 0.6, 1.3)  (p=0.5 -> neutral 1.0x)

Usage:
    python meta_label.py --prefix stock      # train after the primary
    python meta_label.py                     # crypto
"""

import argparse
import json
import math
import os
import sys
from pathlib import Path

import numpy as np

BASE_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(BASE_DIR))

META_VETO_PROB = 0.30
META_THRESHOLD_FRACTION = 0.5   # replay entries at 0.5x live threshold
HOLDOUT_FRACTION = 0.12         # keep in sync with hypersearch_v2

# Feature names must exist BOTH in the harvest dataframe and in the live
# prediction snapshot (predict_now._SNAPSHOT_COLS) — plus the prediction
# itself and the entry hour. Missing values become 0.0 on both sides.
META_FEATURES = [
    'pred', 'RSI', 'Price_SMA20_Ratio', 'BBB_20_2.0', 'Volatility_12h',
    'Return_4h', 'Return_12h', 'ATR_Pct', 'Daily_Sentiment', 'Hurst',
    'hour_sin', 'hour_cos',
    # Return-of-day (BDS 2025): SOFT feature only — the meta-learner can
    # discover the PM-window loser-bounce interaction with hour_sin/cos;
    # a hard rule died in red-team (winner-leg effect is ~0)
    'ROD_Ret',
]


def _paths(prefix: str) -> dict:
    p = f'{prefix}_' if prefix else ''
    return {
        'model': BASE_DIR / f'{p}meta_model.txt',
        'calib': BASE_DIR / f'{p}meta_calib.pkl',
        'meta': BASE_DIR / f'{p}meta_meta.json',
    }


# ---------------------------------------------------------------------------
# Feature construction (single source for training + live)
# ---------------------------------------------------------------------------

def _hour_encode(hour: float) -> tuple[float, float]:
    ang = 2 * math.pi * hour / 24.0
    return math.sin(ang), math.cos(ang)


def build_feature_matrix(tdf, preds) -> np.ndarray:
    """Per-bar meta features from a harvest-style DataFrame (training)."""
    n = len(tdf)
    # Single hour pass feeding both trig columns — vectorized twin of
    # _hour_encode (the live scalar path); keep the two in sync.
    hours = (tdf.index.hour.to_numpy(dtype=np.float64)
             if hasattr(tdf.index, 'hour')
             else np.array([t.hour for t in tdf.index], dtype=np.float64))
    hour_ang = 2 * np.pi * hours / 24.0
    cols = {}
    for name in META_FEATURES:
        if name == 'pred':
            cols[name] = np.asarray(preds, dtype=np.float64)
        elif name == 'hour_sin':
            cols['hour_sin'] = np.sin(hour_ang)
        elif name == 'hour_cos':
            cols['hour_cos'] = np.cos(hour_ang)
        elif name in tdf.columns:
            cols[name] = tdf[name].values.astype(np.float64)
        else:
            cols[name] = np.zeros(n, dtype=np.float64)
    mat = np.column_stack([cols[name] for name in META_FEATURES])
    return np.nan_to_num(mat, nan=0.0, posinf=0.0, neginf=0.0)


def features_from_snapshot(snapshot: dict, pred: float,
                           hour: float | None = None) -> np.ndarray:
    """Live feature vector from the loop's indicator snapshot."""
    if hour is None:
        from datetime import datetime, timezone
        hour = datetime.now(timezone.utc).hour
    hs, hc = _hour_encode(hour)
    vals = []
    for name in META_FEATURES:
        if name == 'pred':
            vals.append(float(pred) if pred is not None else 0.0)
        elif name == 'hour_sin':
            vals.append(hs)
        elif name == 'hour_cos':
            vals.append(hc)
        else:
            v = snapshot.get(name)
            try:
                v = float(v)
                if not np.isfinite(v):
                    v = 0.0
            except (TypeError, ValueError):
                v = 0.0
            vals.append(v)
    return np.asarray(vals, dtype=np.float64)


# ---------------------------------------------------------------------------
# Live / backtest scoring
# ---------------------------------------------------------------------------

_loaded: dict[str, tuple] = {}   # prefix -> (artifact stat key, result)


def _stat_key(paths: dict) -> tuple:
    """(model_mtime_ns, calib_mtime_ns); None for a missing file.

    The key changes when artifacts are retrained, deleted (shadow
    promotion), or first appear — so _load self-heals without a restart.
    """
    key = []
    for k in ('model', 'calib'):
        try:
            key.append(os.stat(paths[k]).st_mtime_ns)
        except OSError:
            key.append(None)
    return tuple(key)


def _read_artifacts(paths: dict) -> tuple:
    """Load (booster, calibrator) from disk. Split out so tests can stub it."""
    import joblib
    import lightgbm as lgb
    booster = lgb.Booster(model_file=str(paths['model']))
    calib = joblib.load(paths['calib'])
    return booster, calib


def _load(prefix: str):
    """(booster, calib) for `prefix`, or None when the meta layer is absent.

    Cache contract (2026-07 review P1): keyed on the artifact files'
    mtimes, re-stat'd on every call (two os.stat per candidate — cheap).
    A weekly meta retrain, a shadow promotion that DELETES the champion
    meta files (the gate then fails open to neutral, per shadow.py), or
    the first meta train landing in an already-running bot all take
    effect without a process restart. A load failure is cached as None
    under the same key (no per-bar retry storm) and retried as soon as
    the files change.
    """
    paths = _paths(prefix)
    key = _stat_key(paths)
    cached = _loaded.get(prefix)
    if cached is not None and cached[0] == key:
        return cached[1]
    result = None
    if None not in key:
        try:
            result = _read_artifacts(paths)
        except Exception as e:
            print(f"[META] load failed ({e}) — meta layer disabled")
            result = None
    _loaded[prefix] = (key, result)
    return result


def invalidate_cache():
    _loaded.clear()


_calib_fallback_warned = False


def _calibrated(calib, raw: np.ndarray) -> np.ndarray:
    global _calib_fallback_warned
    try:
        return np.clip(calib.predict(raw), 0.0, 1.0)
    except Exception as e:
        if not _calib_fallback_warned:
            _calib_fallback_warned = True
            print(f"[META] calibrator predict failed ({e}) — serving raw scores")
        return np.clip(raw, 0.0, 1.0)


def meta_probability_live(prefix: str, snapshot: dict, pred: float) -> float | None:
    """Calibrated P(trade profits net of costs) for a live candidate.

    Returns None when no meta model exists — the layer is strictly
    optional and absent models leave behavior unchanged.
    """
    loaded = _load(prefix)
    if loaded is None:
        return None
    booster, calib = loaded
    x = features_from_snapshot(snapshot, pred).reshape(1, -1)
    raw = booster.predict(x)
    return float(_calibrated(calib, np.asarray(raw))[0])


def predict_meta_array(prefix: str, tdf, preds) -> np.ndarray | None:
    """Per-bar meta probabilities for the backtester (policy parity)."""
    loaded = _load(prefix)
    if loaded is None:
        return None
    booster, calib = loaded
    mat = build_feature_matrix(tdf, preds)
    raw = booster.predict(mat)
    return _calibrated(calib, np.asarray(raw))


def meta_size_mult(p: float | None) -> float:
    """Bounded sizing multiplier from the calibrated probability."""
    if p is None:
        return 1.0
    return float(np.clip(2.0 * p, 0.6, 1.3))


# ---------------------------------------------------------------------------
# Training
# ---------------------------------------------------------------------------

def _gen_meta_rows(tdf, preds, asset_type, threshold, policy):
    """Replay the primary's signals through the live exit stack.

    Entries at META_THRESHOLD_FRACTION x the live threshold so the meta
    model also sees the marginal signals it should learn to veto.
    Returns (features, labels, net_returns, entry_times, exit_times).
    """
    from policy_exits import exit_walk, eod_mask_from_index
    from fees import round_trip_cost_pct

    closes = tdf['Close'].values
    highs = tdf['High'].values if 'High' in tdf.columns else closes
    lows = tdf['Low'].values if 'Low' in tdf.columns else closes
    opens = tdf['Open'].values if 'Open' in tdf.columns else closes
    atr = tdf['ATR'].values if 'ATR' in tdf.columns else np.full(len(closes), np.nan)
    is_eod = eod_mask_from_index(tdf.index, asset_type)

    spread = 0.10 if asset_type == 'crypto' else 0.05
    rt_cost = round_trip_cost_pct(asset_type, spread)
    # Per-bar effective-spread cost when the harvest stamped it (wave 6):
    # removes the train/deploy asymmetry vs the real-spread live gate. Falls
    # back to the flat rt_cost per bar when Eff_Spread_Pct is absent.
    rt_cost_arr = None
    if 'Eff_Spread_Pct' in tdf.columns:
        try:
            from liquidity import per_bar_round_trip_cost, impact_inputs_from_df
            # Optional sqrt market-impact haircut (wave-8 #6), off by default so
            # the meta labels are unchanged unless explicitly enabled + DV30 present.
            adv_arr, impact_notional, impact_k = impact_inputs_from_df(tdf)
            rt_cost_arr = per_bar_round_trip_cost(
                asset_type, tdf['Eff_Spread_Pct'].values,
                adv_dollar=adv_arr, notional=impact_notional, impact_k=impact_k)
        except Exception as e:
            print(f"[META] per-bar spread cost failed ({e}) — flat-cost fallback")
            rt_cost_arr = None
    cooldown_bars = max(1, int(math.ceil(policy['cooldown_min'] / 60)))
    entry_threshold = threshold * META_THRESHOLD_FRACTION

    exit_idx, exit_px, _reason = exit_walk(
        closes, highs, lows, opens, atr, is_eod, policy,
        preds=preds, threshold=threshold, cooldown_bars=cooldown_bars,
        max_hold=0, use_signal_exit=True)

    feats_all = build_feature_matrix(tdf, preds)
    rows, labels, nets, times, exit_times = [], [], [], [], []
    n = len(closes)
    i = 0
    next_entry = 0
    while i < n - 1:
        p = preds[i]
        if (np.isnan(p) or i < next_entry or p < entry_threshold
                or is_eod[i]):
            i += 1
            continue
        j = int(exit_idx[i])
        cost_i = rt_cost if rt_cost_arr is None else float(rt_cost_arr[i])
        net = (float(exit_px[i]) - closes[i]) / closes[i] * 100.0 - cost_i
        rows.append(feats_all[i])
        labels.append(1 if net > 0 else 0)
        nets.append(net)
        times.append(tdf.index[i])
        exit_times.append(tdf.index[j])   # label span end, for the purged calibration
        next_entry = j + cooldown_bars
        i = j + 1
    return rows, labels, nets, times, exit_times


def train_meta(prefix: str = '') -> bool:
    import joblib
    try:
        import lightgbm as lgb
    except ImportError:
        print("[META] lightgbm not installed — skipping meta layer")
        return False
    from sklearn.isotonic import IsotonicRegression
    from data_utils import load_training_data
    from strategy_config import policy_for
    from backtest import _load_artifacts, _predict_ticker, _load_lgb

    asset_type = prefix or 'crypto'
    try:
        model, scaler, config, feature_cols = _load_artifacts(prefix)
    except FileNotFoundError:
        print("[META] primary model artifacts missing — train the primary first")
        return False
    lgb_primary = _load_lgb(prefix)
    threshold = config.get('trade_threshold', 0.15)
    policy = policy_for(asset_type)

    df = load_training_data('stock' if prefix == 'stock' else 'crypto')
    if df.empty:
        print("[META] no training data")
        return False

    # Exclude the hypersearch holdout (final 12% of calendar time) so the
    # policy gate evaluates a meta model that never saw that window
    times_ns = df.index.view('int64')
    cutoff = np.quantile(times_ns, 1.0 - HOLDOUT_FRACTION)

    X, y, ts, exit_ts = [], [], [], []
    for ticker in df['Ticker'].unique():
        tdf = df[df['Ticker'] == ticker].sort_index()
        tdf = tdf[tdf.index.view('int64') <= cutoff]
        if len(tdf) < config['seq_len'] + 50:
            continue
        if any(c not in tdf.columns for c in feature_cols):
            continue
        preds, _ = _predict_ticker(model, scaler, config, feature_cols, tdf,
                                   lgb_model=lgb_primary)
        r, l, _nr, t, et = _gen_meta_rows(tdf, preds, asset_type, threshold, policy)
        X.extend(r); y.extend(l); ts.extend(t); exit_ts.extend(et)
        print(f"  [META] {ticker}: {len(r)} replayed trades")

    if len(X) < 200:
        print(f"[META] only {len(X)} replayed trades — not enough to train")
        return False

    order = np.argsort(np.asarray(ts))
    X = np.asarray(X)[order]
    y = np.asarray(y)[order]
    split = int(len(X) * 0.8)  # chronological split for early stop + calibration
    train_set = lgb.Dataset(X[:split], label=y[:split],
                            feature_name=META_FEATURES)
    val_set = lgb.Dataset(X[split:], label=y[split:], reference=train_set)
    params = {
        'objective': 'binary', 'metric': 'auc',
        'num_leaves': 31, 'max_depth': 5, 'learning_rate': 0.05,
        'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5,
        'verbose': -1, 'n_jobs': 4,
    }
    booster = lgb.train(params, train_set, num_boost_round=400,
                        valid_sets=[val_set],
                        callbacks=[lgb.early_stopping(30, verbose=False)])

    # Probability calibration. Default 'legacy' = the original same-slice isotonic
    # (the leak: it fits on the exact X[split:] slice the booster early-stopped on).
    # 'purged_oof' (wave-9 #1) calibrates on PURGED out-of-fold predictions so the
    # calibrator never sees a slice the model peeked at, removing the upward p-bias
    # that drives the live veto + size multiplier. Fail-open to legacy.
    from strategy_config import META_CALIBRATION_MODE
    calib = None
    if META_CALIBRATION_MODE == 'purged_oof':
        try:
            from calibration import crossfit_oof_predict, fit_calibrator
            entry_e = np.array([t.timestamp() for t in np.asarray(ts)[order]], float)
            exit_e = np.array([t.timestamp() for t in np.asarray(exit_ts)[order]], float)
            n_iter = int(booster.best_iteration or 200)

            def _fold_fit_predict(Xtr, ytr, Xte):
                ds = lgb.Dataset(Xtr, label=ytr, feature_name=META_FEATURES)
                b = lgb.train(params, ds, num_boost_round=n_iter)
                return b.predict(Xte)

            oof = crossfit_oof_predict(_fold_fit_predict, X, y, entry_e, exit_e,
                                       k=5, embargo=0.0)
            calib = fit_calibrator(oof, y)
            if calib is not None:
                print(f"[META] purged out-of-fold calibration "
                      f"({type(calib).__name__}, {int(np.isfinite(oof).sum())} OOF rows)")
        except Exception as e:
            print(f"[META] purged calibration failed ({e}) — falling back to legacy")
            calib = None
    if calib is None:
        raw_val = booster.predict(X[split:])
        calib = IsotonicRegression(out_of_bounds='clip').fit(raw_val, y[split:])

    # .prev backups so the policy gate can roll the meta layer back
    import shutil
    paths = _paths(prefix)
    for key in ('model', 'calib', 'meta'):
        if paths[key].exists():
            try:
                shutil.copy2(paths[key], str(paths[key]) + '.prev')
            except OSError:
                pass

    # Atomic publish (tmp + os.replace): a bot's mtime-keyed _load can never
    # read a half-written file. Calib is replaced FIRST, model LAST, so a
    # reader waking on the model swap sees the paired calibrator already in
    # place. (Strict cross-file pairing atomicity would need a manifest —
    # deferred; the remaining window is two adjacent os.replace calls.)
    tmp_model = str(paths['model']) + '.tmp'
    tmp_calib = str(paths['calib']) + '.tmp'
    booster.save_model(tmp_model)
    joblib.dump(calib, tmp_calib)
    os.replace(tmp_calib, paths['calib'])
    os.replace(tmp_model, paths['model'])
    base_rate = float(np.mean(y))
    tmp_meta = str(paths['meta']) + '.tmp'
    with open(tmp_meta, 'w') as f:
        json.dump({
            'features': META_FEATURES,
            'n_trades': int(len(X)),
            'base_win_rate': round(base_rate, 4),
            'val_auc': round(float(booster.best_score['valid_0']['auc']), 4),
            'threshold_fraction': META_THRESHOLD_FRACTION,
        }, f, indent=2)
    os.replace(tmp_meta, paths['meta'])
    invalidate_cache()
    print(f"[META] saved {paths['model'].name}: {len(X)} trades, "
          f"base win-rate {base_rate:.3f}, "
          f"val AUC {booster.best_score['valid_0']['auc']:.3f}")
    return True


if __name__ == '__main__':
    ap = argparse.ArgumentParser(description='Train the meta-labeling layer')
    ap.add_argument('--prefix', default='', help="'' crypto, 'stock' stocks")
    args = ap.parse_args()
    train_meta(args.prefix)  # graceful False is non-fatal in the pipeline
    sys.exit(0)  # NOTE: an uncaught crash still exits 1 — crash-tolerance is decision-queued
